<?php
/**
 * Implements hook_ctools_plugin_directory().
 */
function csc_directors_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme
 */ 
function csc_directors_theme() {
    return array(

        'csc_directors_item' => array(
          'render element' => 'element',
          'file' => 'plugins/content_types/csc_directors.inc',
        ),
    );
}
